;;; Transpiled from lsim.fol by FOL compiler

;;; This file was automatically generated. Do not edit directly.

(DEFVAR *MODULES* (ATOM (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT)))

(DEFUN REGISTER-MODULE (NAME DEF)
  (FOL.COMPILER.MUTABLE:SWAP! *MODULES* #'ASSOC NAME DEF))

(DEFUN GET-MODULE (NAME) (GET (FOL.COMPILER.MUTABLE:DEREF *MODULES*) NAME))

(PROGN
 (DEFCLASS <COMPONENT> (FOL.COMPILER.PERSISTENT:<PERSISTENT-OBJECT>)
           ((NAME :INITARG :NAME) (TYPE :INITARG :TYPE)
            (CONNECTIONS :INITARG :CONNECTIONS))
           (:METACLASS FOL.COMPILER.PERSISTENT:PERSISTENT-CLASS))
 (DEFUN COMPONENT-NAME (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT) :NAME))
 (DEFUN COMPONENT-TYPE (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT) :TYPE))
 (DEFUN COMPONENT-CONNECTIONS (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT)
    :CONNECTIONS))
 (DEFUN MAKE-<COMPONENT> (&KEY NAME TYPE CONNECTIONS)
   (MAKE-INSTANCE '<COMPONENT> :NAME NAME :TYPE TYPE :CONNECTIONS CONNECTIONS))
 '<COMPONENT>)

(PROGN
 (DEFCLASS <MODULE-DEF> (FOL.COMPILER.PERSISTENT:<PERSISTENT-OBJECT>)
           ((NAME :INITARG :NAME) (PORTS :INITARG :PORTS)
            (BODY :INITARG :BODY))
           (:METACLASS FOL.COMPILER.PERSISTENT:PERSISTENT-CLASS))
 (DEFUN MODULE-NAME (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT) :NAME))
 (DEFUN MODULE-PORTS (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT)
    :PORTS))
 (DEFUN MODULE-BODY (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT) :BODY))
 (DEFUN MAKE-<MODULE-DEF> (&KEY NAME PORTS BODY)
   (MAKE-INSTANCE '<MODULE-DEF> :NAME NAME :PORTS PORTS :BODY BODY))
 '<MODULE-DEF>)

(PROGN
 (DEFCLASS <LOGIC-COMPONENT>
           (<COMPONENT> FOL.COMPILER.PERSISTENT:<PERSISTENT-OBJECT>)
           ((INPUTS :INITARG :INPUTS) (OUTPUTS :INITARG :OUTPUTS)
            (DELAYS :INITARG :DELAYS) (LOGIC-FN :INITARG :LOGIC-FN))
           (:METACLASS FOL.COMPILER.PERSISTENT:PERSISTENT-CLASS))
 (DEFUN COMPONENT-INPUTS (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT)
    :INPUTS))
 (DEFUN COMPONENT-OUTPUTS (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT)
    :OUTPUTS))
 (DEFUN COMPONENT-DELAYS (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT)
    :DELAYS))
 (DEFUN COMPONENT-LOGIC-FN (FOL.COMPILER::OBJECT)
   (SYCAMORE:HASH-MAP-FIND
    (FOL.COMPILER.PERSISTENT::%PERSISTENT-STORAGE FOL.COMPILER::OBJECT)
    :LOGIC-FN))
 (DEFUN MAKE-<LOGIC-COMPONENT> (&KEY INPUTS OUTPUTS DELAYS LOGIC-FN)
   (MAKE-INSTANCE '<LOGIC-COMPONENT> :INPUTS INPUTS :OUTPUTS OUTPUTS :DELAYS
                  DELAYS :LOGIC-FN LOGIC-FN))
 '<LOGIC-COMPONENT>)

(DEFGENERIC COMPUTE-NEXT-STATE
    (COMP INPUT-STATES CHANGED-INPUTS))

(DEFUN COMPUTE-NEXT-STATE (COMP INPUT-STATES CHANGED-INPUTS)
  (COND
   ((TYPEP COMP '<LOGIC-COMPONENT>)
    (LET ((LOGIC-FN (COMPONENT-LOGIC-FN COMP)))
      (LET ((DELAYS (COMPONENT-DELAYS COMP)))
        (LET ((NEW-STATES (LOGIC-FN INPUT-STATES)))
          (MAP
           (LAMBDA (OUT-PORT)
             (LET ((DELAY
                    (REDUCE
                     (LAMBDA (MAX-D IN-PORT)
                       (LET ((D (GET (GET DELAYS IN-PORT) OUT-PORT)))
                         (IF (FOL.COMPILER.PRIMITIVES:TRUTHY?
                              (AND D (> D MAX-D)))
                             D
                             MAX-D)))
                     0 CHANGED-INPUTS)))
               (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :VALUE
                                                   (GET NEW-STATES OUT-PORT)
                                                   :DELAY DELAY :PORT
                                                   OUT-PORT)))
           (COMPONENT-OUTPUTS COMP))))))
   (T
    (ERROR "No matching method clause for ~A with arguments: ~S"
           'COMPUTE-NEXT-STATE (LIST COMP INPUT-STATES CHANGED-INPUTS)))))

(DEFVAR *PRIMITIVES* (ATOM (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT)))

(DEFUN REGISTER-PRIMITIVE (NAME FACTORY)
  (FOL.COMPILER.MUTABLE:SWAP! *PRIMITIVES* #'ASSOC NAME FACTORY))

(DEFUN GET-PRIMITIVE (NAME)
  (GET (FOL.COMPILER.MUTABLE:DEREF *PRIMITIVES*) NAME))

(REGISTER-PRIMITIVE 'NOT
 (LAMBDA (NAME PARAM CONNS)
   (MAKE <LOGIC-COMPONENT> :NAME NAME :TYPE 'NOT :CONNECTIONS CONNS :INPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :IN) :OUTPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :OUT) :DELAYS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :IN
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 1))
    :LOGIC-FN
    (LAMBDA (S) (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :OUT (NOT (GET S :IN)))))))

(REGISTER-PRIMITIVE 'NAND
 (LAMBDA (NAME PARAM CONNS)
   (MAKE <LOGIC-COMPONENT> :NAME NAME :TYPE 'NAND :CONNECTIONS CONNS :INPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :IN2 :IN1) :OUTPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :OUT) :DELAYS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :IN2
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 2)
                                        :IN1
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 2))
    :LOGIC-FN
    (LAMBDA (S)
      (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :OUT
                                          (NOT
                                           (AND (GET S :IN1) (GET S :IN2))))))))

(REGISTER-PRIMITIVE 'NOR
 (LAMBDA (NAME PARAM CONNS)
   (MAKE <LOGIC-COMPONENT> :NAME NAME :TYPE 'NOR :CONNECTIONS CONNS :INPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :IN2 :IN1) :OUTPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :OUT) :DELAYS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :IN2
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 2)
                                        :IN1
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 2))
    :LOGIC-FN
    (LAMBDA (S)
      (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :OUT
                                          (NOT
                                           (OR (GET S :IN1) (GET S :IN2))))))))

(REGISTER-PRIMITIVE 'AND
 (LAMBDA (NAME PARAM CONNS)
   (MAKE <LOGIC-COMPONENT> :NAME NAME :TYPE 'AND :CONNECTIONS CONNS :INPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :IN2 :IN1) :OUTPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :OUT) :DELAYS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :IN2
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 3)
                                        :IN1
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 3))
    :LOGIC-FN
    (LAMBDA (S)
      (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :OUT
                                          (AND (GET S :IN1) (GET S :IN2)))))))

(REGISTER-PRIMITIVE 'OR
 (LAMBDA (NAME PARAM CONNS)
   (MAKE <LOGIC-COMPONENT> :NAME NAME :TYPE 'OR :CONNECTIONS CONNS :INPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :IN2 :IN1) :OUTPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :OUT) :DELAYS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :IN2
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 3)
                                        :IN1
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 3))
    :LOGIC-FN
    (LAMBDA (S)
      (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :OUT
                                          (OR (GET S :IN1) (GET S :IN2)))))))

(REGISTER-PRIMITIVE 'XOR
 (LAMBDA (NAME PARAM CONNS)
   (MAKE <LOGIC-COMPONENT> :NAME NAME :TYPE 'XOR :CONNECTIONS CONNS :INPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :IN2 :IN1) :OUTPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :OUT) :DELAYS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :IN2
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 3)
                                        :IN1
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 3))
    :LOGIC-FN
    (LAMBDA (S)
      (LET ((A (GET S :IN1)))
        (LET ((B (GET S :IN2)))
          (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :OUT
                                              (OR (AND A (NOT B))
                                                  (AND (NOT A) B)))))))))

(REGISTER-PRIMITIVE 'XNOR
 (LAMBDA (NAME PARAM CONNS)
   (MAKE <LOGIC-COMPONENT> :NAME NAME :TYPE 'XNOR :CONNECTIONS CONNS :INPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :IN2 :IN1) :OUTPUTS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :OUT) :DELAYS
    (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :IN2
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 4)
                                        :IN1
                                        (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                         :OUT 4))
    :LOGIC-FN
    (LAMBDA (S)
      (LET ((A (GET S :IN1)))
        (LET ((B (GET S :IN2)))
          (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :OUT
                                              (NOT
                                               (OR (AND A (NOT B))
                                                   (AND (NOT A) B))))))))))

(REGISTER-PRIMITIVE 'DELAY
 (LAMBDA (NAME PARAM CONNS)
   (LET ((D (OR PARAM 0)))
     (MAKE <LOGIC-COMPONENT> :NAME NAME :TYPE 'DELAY :CONNECTIONS CONNS :INPUTS
      (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :IN) :OUTPUTS
      (FOL.COMPILER.CL-UTILS:MAKE-CL-SET :OUT) :DELAYS
      (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :IN
                                          (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT
                                           :OUT D))
      :LOGIC-FN
      (LAMBDA (S) (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :OUT (GET S :IN)))))))

(DEFMACRO DEFPART (NAME PORTS &BODY BODY)
  `(REGISTER-MODULE ',NAME
    (MAKE <MODULE-DEF> :NAME ',NAME :PORTS ',PORTS :BODY ',BODY)))

(DEFUN QUALIFY-NAME (PREFIX NAME)
  (IF (FOL.COMPILER.PRIMITIVES:TRUTHY? (NIL? PREFIX))
      NAME
      (SYMBOL (STR PREFIX "/" NAME))))

(DEFUN RESOLVE-NODE (NODE-SYM PREFIX BINDINGS)
  (IF (FOL.COMPILER.PRIMITIVES:TRUTHY? (CONTAINS? BINDINGS NODE-SYM))
      (GET BINDINGS NODE-SYM)
      (QUALIFY-NAME PREFIX NODE-SYM)))

(DEFUN PARSE-CONNECTIONS (ARGS PREFIX BINDINGS)
  (BLOCK #:LOOP-BLOCK-273
    (LET ((REM ARGS) (ACC (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT)))
      (TAGBODY
       #:LOOP-274
        (LET ((#:RESULT-275
               (PROGN
                (IF (FOL.COMPILER.PRIMITIVES:TRUTHY? (EMPTY? REM))
                    ACC
                    (LET ((PORT (FIRST REM)))
                      (LET ((NODE-SYM (SECOND REM)))
                        (LET ((RESOLVED
                               (RESOLVE-NODE NODE-SYM PREFIX BINDINGS)))
                          (PROGN
                           (PSETQ REM (REST (REST REM))
                                  ACC (ASSOC ACC PORT RESOLVED))
                           (GO #:LOOP-274)))))))))
          (RETURN-FROM #:LOOP-BLOCK-273 #:RESULT-275))))))

(DEFUN EXPAND-NETLIST (TOP-MODULE-NAME)
  (LET ((DEF (GET-MODULE TOP-MODULE-NAME)))
    (IF (FOL.COMPILER.PRIMITIVES:TRUTHY? (NIL? DEF))
        (ERROR (STR "Module " TOP-MODULE-NAME " not found"))
        (LET ((TOP-BINDINGS
               (REDUCE (LAMBDA (ACC P) (ASSOC ACC P P))
                       (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT)
                       (MODULE-PORTS DEF))))
          (REDUCE
           (LAMBDA (ACC SPEC) (CONCAT ACC (EXPAND-SPEC SPEC NIL TOP-BINDINGS)))
           (FOL.COMPILER.CL-UTILS:MAKE-CL-VECTOR) (MODULE-BODY DEF))))))

(DEFGENERIC REGISTER-CONNECTIVITY
    (COMP MAP))

(DEFMETHOD REGISTER-CONNECTIVITY (COMP MAP) MAP)

(DEFUN REGISTER-CONNECTIVITY (COMP MAP)
  (COND
   ((TYPEP COMP '<LOGIC-COMPONENT>)
    (REDUCE
     (LAMBDA (ACC PORT)
       (LET ((NODE (GET (COMPONENT-CONNECTIONS COMP) PORT)))
         (UPDATE ACC NODE
          (LAMBDA (COMPS)
            (CONJ (OR COMPS (FOL.COMPILER.CL-UTILS:MAKE-CL-VECTOR)) COMP)))))
     MAP (COMPONENT-INPUTS COMP)))
   (T
    (ERROR "No matching method clause for ~A with arguments: ~S"
           'REGISTER-CONNECTIVITY (LIST COMP MAP)))))

(DEFUN INSERT-EVENT (QUEUE EVENT)
  (IF (FOL.COMPILER.PRIMITIVES:TRUTHY? (EMPTY? QUEUE))
      (FOL.COMPILER.CL-UTILS:MAKE-CL-VECTOR EVENT)
      (LET ((HEAD (FIRST QUEUE)))
        (IF (FOL.COMPILER.PRIMITIVES:TRUTHY?
             (< (GET EVENT :TIME) (GET HEAD :TIME)))
            (CONS EVENT QUEUE)
            (CONS HEAD (INSERT-EVENT (REST QUEUE) EVENT))))))

(DEFUN MERGE-EVENTS (QUEUE NEW-EVENTS) (REDUCE INSERT-EVENT QUEUE NEW-EVENTS))

(DEFUN GET-INPUT-STATES (COMP NODE-VALUES)
  (REDUCE
   (LAMBDA (ACC PORT)
     (LET ((NODE (GET (COMPONENT-CONNECTIONS COMP) PORT)))
       (ASSOC ACC PORT (GET NODE-VALUES NODE))))
   (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT) (COMPONENT-INPUTS COMP)))

(DEFUN GET-CHANGED-PORTS (COMP CHANGED-NODES)
  (FILTER
   (LAMBDA (PORT)
     (LET ((NODE (GET (COMPONENT-CONNECTIONS COMP) PORT)))
       (CONTAINS? CHANGED-NODES NODE)))
   (COMPONENT-INPUTS COMP)))

(DEFVAR *SIM-CONTEXT*
  (ATOM
   (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT :EVENTS
                                       (FOL.COMPILER.CL-UTILS:MAKE-CL-VECTOR)
                                       :MONITORED
                                       (FOL.COMPILER.CL-UTILS:MAKE-CL-SET)
                                       :HISTORY
                                       (FOL.COMPILER.CL-UTILS:MAKE-CL-DICT))))

(DEFUN MONITOR (&REST NODES)
  (FOL.COMPILER.MUTABLE:SWAP! *SIM-CONTEXT* #'UPDATE :MONITORED
                              (LAMBDA (S)
                                (INTO
                                 (OR S (FOL.COMPILER.CL-UTILS:MAKE-CL-SET))
                                 NODES))))

(DEFUN EVENTS (&REST EVENTS)
  (FOL.COMPILER.MUTABLE:SWAP! *SIM-CONTEXT* #'UPDATE :EVENTS
                              (LAMBDA (Q) (CONCAT Q EVENTS))))

(DEFUN RUN (MODULE-NAME TIME)
  (LET ((NETLIST (EXPAND-NETLIST MODULE-NAME)))
    (LET ((INITIAL-EVENTS
           (GET (FOL.COMPILER.MUTABLE:DEREF *SIM-CONTEXT*) :EVENTS)))
      (LET ((MONITORED
             (GET (FOL.COMPILER.MUTABLE:DEREF *SIM-CONTEXT*) :MONITORED)))
        (LET ((HISTORY (RUN-SIMULATION NETLIST INITIAL-EVENTS TIME MONITORED)))
          (PROGN
           (FOL.COMPILER.MUTABLE:SWAP! *SIM-CONTEXT* #'ASSOC :HISTORY HISTORY)
           :SIMULATION-COMPLETE))))))

(DEFUN DISPLAY (&REST NODES)
  (LET ((HISTORY (GET (FOL.COMPILER.MUTABLE:DEREF *SIM-CONTEXT*) :HISTORY)))
    (MAP
     (LAMBDA (NODE)
       (PRINT (STR "Events for " NODE ":"))
       (LET ((EVTS (GET HISTORY NODE)))
         (IF (FOL.COMPILER.PRIMITIVES:TRUTHY? (EMPTY? EVTS))
             (PRINT "  (no events)")
             (MAP
              (LAMBDA (E)
                (PRINT (STR "  T=" (GET E :TIME) " V=" (GET E :VALUE))))
              EVTS))))
     NODES)))

