(defsystem "bootstrap"
  :description "Functional Object Lisp - Bootstrap Implementation."
  :depends-on ("fset" "closer-mop" "cl-ppcre" "uuid" "sycamore" "bordeaux-threads" "lparallel")
  :components ((:file "package")
               (:file "persistent" :depends-on ("package"))
               ;; Classes load BEFORE collection to define constants
               (:file "classes" :depends-on ("package" "persistent"))
               (:file "wrappers" :depends-on ("package" "classes"))
               (:file "collection" :depends-on ("persistent" "wrappers"))
               (:file "env" :depends-on ("collection" "wrappers"))
               (:file "module" :depends-on ("persistent" "collection" "wrappers" "env"))
               (:file "logop"   :depends-on ("package" "classes" "wrappers"))
               (:file "bitop"   :depends-on ("package" "classes" "wrappers"))
               (:file "arithop" :depends-on ("package" "classes" "wrappers"))
               (:file "compareop" :depends-on ("package" "classes" "wrappers" "persistent"))
               (:file "bool"   :depends-on ("package" "wrappers"))
               (:file "char"   :depends-on ("package" "wrappers"))
               (:file "string"   :depends-on ("package" "wrappers" "collection"))
               (:file "seqop"  :depends-on ("package" "wrappers" "collection" "string"))
               (:file "symbol"   :depends-on ("package" "wrappers"))
               (:file "number" :depends-on ("package" "wrappers"))
               (:file "stream" :depends-on ("package" "classes"))
               (:file "reader" :depends-on ("package" "classes" "collection"))
               (:file "mop" :depends-on ("package" "persistent"))
               (:file "fol-mop" :depends-on ("package" "collection"))
               (:file "eval" :depends-on ("package" "wrappers" "classes" "collection" "env"
                                          "logop" "arithop" "compareop" "fol-mop"))
               (:file "standard-names" :depends-on ("eval" "module"))
               (:file "repl" :depends-on ("eval" "reader")))
  :in-order-to ((test-op (test-op "bootstrap/tests"))))

(defsystem "bootstrap/tests"
  :depends-on ("bootstrap" "fiveam")
  :components ((:module "tests"
                 :components
                 ((:file "tests-package")
                  (:file "coverage" :depends-on ("tests-package"))
                  (:file "test-bool"   :depends-on ("tests-package"))
                  (:file "test-char"   :depends-on ("tests-package"))
                  (:file "test-string"   :depends-on ("tests-package"))
                  (:file "test-symbol"   :depends-on ("tests-package"))
                  (:file "test-number" :depends-on ("tests-package"))
                  (:file "test-reader" :depends-on ("tests-package"))
                  (:file "test-wrappers" :depends-on ("tests-package"))
                  (:file "test-logop" :depends-on ("tests-package"))
                  (:file "test-arithop" :depends-on ("tests-package"))
                  (:file "test-compareop" :depends-on ("tests-package"))
                  (:file "test-persistent" :depends-on ("tests-package"))
                  (:file "test-collection" :depends-on ("tests-package"))
                  (:file "test-dict" :depends-on ("tests-package"))
                  (:file "test-seqop" :depends-on ("tests-package"))
                  (:file "test-module" :depends-on ("tests-package"))
                  (:file "test-env" :depends-on ("tests-package"))
                  (:file "test-mop" :depends-on ("tests-package"))
                  (:file "test-mop-constructors" :depends-on ("tests-package"))
                  (:file "test-fol-mop" :depends-on ("tests-package"))
                  (:file "test-stream" :depends-on ("tests-package"))
                  (:file "test-eval" :depends-on ("tests-package"))
                  (:file "test-transducers" :depends-on ("tests-package"))
                  (:file "test-zip" :depends-on ("tests-package"))
                  )))
  :perform (test-op (o s) (symbol-call :fol.tests :run-fol-tests)))
