(with-open-file (s "c:/Users/frank/Projects/FOL/fol/src/collection-primitives.lisp")
  (let ((count 0)
        (line 1)
        (col 0)
        (in-string nil)
        (in-comment nil)
        (in-block-comment 0))
    (loop
     (let ((c (read-char s nil :eof)))
       (if (eq c :eof)
           (return (format t "Final Balance: ~D~%" count))
           (progn
            (incf col)
            (cond
             ((> in-block-comment 0)
               (cond ((eq c #\|)
                       (let ((next (read-char s nil :eof)))
                         (if (eq next #\#) (decf in-block-comment)
                             (unread-char next s))))
                     ((eq c #\#)
                       (let ((next (read-char s nil :eof)))
                         (if (eq next #\|) (incf in-block-comment)
                             (unread-char next s))))
                     ((eq c #\Newline) (incf line) (setf col 0))))
             (in-comment (when (eq c #\Newline) (setf in-comment nil line (1+ line) col 0)))
             (in-string (cond ((eq c #\\) (read-char s)) ; skip escaped char
                              ((eq c #\") (setf in-string nil))))
             (t (cond ((eq c #\#)
                        (let ((next (read-char s nil :eof)))
                          (cond ((eq next #\|) (incf in-block-comment))
                                (t (unread-char next s)))))
                      ((eq c #\;) (setf in-comment t))
                      ((eq c #\") (setf in-string t))
                      ((eq c #\() (incf count)
                                  (when (= count 1) (format t "Form at ~D:~D~%" line col)))
                      ((eq c #\)) (decf count))
                      ((eq c #\Newline) (incf line) (setf col 0)))))))))))
