(require :asdf)
(push (truename "src/") asdf:*central-registry*)
(asdf:load-system :fol-compiler)
(format t "Attempting to transpile...~%")
(handler-case
    (fol.compiler:compile-file "benchmarks/fol-code/compliance.fol" :output "test_compliance.lisp")
  (error (c)
    (format t "ERROR: ~A~%" c)
    (sb-ext:quit :unix-status 1)))
(format t "Done. Check test_compliance.lisp~%")
(sb-ext:quit)
