(defsystem "fol"
  :description "Functional Object Lisp with FSet-based Persistent Objects."
  :depends-on ("named-readtables" "fset" "closer-mop")
  :components ((:file "prefix")
               (:file "package" :depends-on ("prefix"))
               (:file "persistent" :depends-on ("package"))
               (:file "mop" :depends-on ("package" "persistent"))
               ;; Classes and Singleton load BEFORE collection to define constants
               (:file "classes" :depends-on ("package" "persistent"))
               (:file "singleton" :depends-on ("package" "classes"))
               (:file "wrappers" :depends-on ("package" "classes" "singleton"))
               (:file "collection" :depends-on ("persistent" "singleton"))
               (:file "module" :depends-on ("persistent" "singleton"))
               (:file "syntax" :depends-on ("package" "singleton" "wrappers" "collection"))
               (:file "logop"   :depends-on ("package" "classes" "wrappers"))
               (:file "arithop" :depends-on ("package" "classes" "wrappers"))
               (:file "compareop" :depends-on ("package" "classes" "wrappers" "persistent"))
               (:file "bool"   :depends-on ("package" "wrappers" "singleton"))
               (:file "char"   :depends-on ("package" "wrappers"))
               (:file "string"   :depends-on ("package" "wrappers"))
               (:file "symbol"   :depends-on ("package" "wrappers"))
               (:file "number" :depends-on ("package" "wrappers")))
  :in-order-to ((test-op (test-op "fol/tests"))))

(defsystem "fol/tests"
  :depends-on ("fol" "fiveam")
  :components ((:module "tests"
                 :components
                 ((:file "tests-package")
                  (:file "test-bool"   :depends-on ("tests-package"))
                  (:file "test-char"   :depends-on ("tests-package"))
                  (:file "test-string"   :depends-on ("tests-package"))
                  (:file "test-symbol"   :depends-on ("tests-package"))
                  (:file "test-number" :depends-on ("tests-package"))
                  (:file "test-syntax" :depends-on ("tests-package"))
                  (:file "test-wrappers" :depends-on ("tests-package"))
                  (:file "test-logop" :depends-on ("tests-package"))
                  (:file "test-arithop" :depends-on ("tests-package"))
                  (:file "test-compareop" :depends-on ("tests-package"))
                  (:file "test-persistent" :depends-on ("tests-package"))
                  (:file "test-collection" :depends-on ("tests-package"))
                  (:file "test-module" :depends-on ("tests-package"))
                  (:file "test-mop" :depends-on ("tests-package"))
                  )))
  :perform (test-op (o s) (symbol-call :fol.tests :run-fol-tests)))