(push (truename "src/") asdf:*central-registry*)
(asdf:load-system :fol-compiler)

(defun transpile-file (input-file output-file)
  (with-open-file (in input-file)
    (with-open-file (out output-file :direction :output :if-exists :supersede :if-does-not-exist :create)
      (format out ";;; Transpiled from ~A by FOL compiler~%~%" (file-namestring input-file))
      (format out ";;; This file was automatically generated. Do not edit directly.~%~%")
      (let ((*readtable* fol.compiler.reader:*fol-readtable*)
            (*print-circle* t) ;; CRITICAL: Use circle detection for GENSYMs within a form
            (form-count 0)
            (skipped-count 0))
        (loop for form = (read in nil :eof)
              until (eq form :eof)
              do (let ((result (fol.compiler:compile-form form)))
                   (incf form-count)
                   (if (fol.compiler:compilation-result-code result)
                       (let ((code (fol.compiler:compilation-result-code result)))
                         ;; UNWRAP PROGN if it's a package switch
                         (if (and (consp code) 
                                  (member (car code) '(cl:progn progn))
                                  (consp (second code))
                                  (member (car (second code)) '(cl:defpackage defpackage)))
                             (dolist (sub (cdr code))
                               (prin1 sub out)
                               (terpri out)
                               (terpri out))
                             (progn
                               (prin1 code out)
                               (terpri out)
                               (terpri out))))
                       (progn
                         (incf skipped-count)
                         (format t "~%SKIPPED form ~D~%" form-count)
                         (when (fol.compiler:compilation-result-errors result)
                           (format t "ERROR: ~{~A~%~}~%" (fol.compiler:compilation-result-errors result)))))))
        (format t "Total forms: ~D, Skipped: ~D~%" form-count skipped-count)))))

(format t "Re-Transpiling compliance.fol with *PRINT-CIRCLE* and unwrapped PROGN...~%")
(ensure-directories-exist "transpiled-fol-code/")
(transpile-file "benchmarks/fol-code/compliance.fol" "transpiled-fol-code/compliance.lisp")
(format t "✓ Done~%")
(sb-ext:quit)
