import sys

macro_code = """
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defun %pvec-mk-sym (fmt &rest args)
    (intern (apply #'format nil fmt (mapcar #'string args)))))

(defmacro define-pvec-trie (name conc-name leaf-type element-type fallback-val accessor)
  (let* ((make-name (%pvec-mk-sym "%MAKE-~A" (subseq (string name) 1)))
         (pred-name (%pvec-mk-sym "~A?" name))
         (count-acc (%pvec-mk-sym "~ACOUNT" conc-name))
         (shift-acc (%pvec-mk-sym "~ASHIFT" conc-name))
         (root-acc  (%pvec-mk-sym "~AROOT" conc-name))
         (tail-acc  (%pvec-mk-sym "~ATAIL" conc-name))
         
         (api-count    (%pvec-mk-sym "~A-COUNT" name))
         (api-tail-off (%pvec-mk-sym "~A-TAIL-OFF" name))
         (api-ref      (%pvec-mk-sym "~A-REF" name))
         (api-conj     (%pvec-mk-sym "~A-CONJ" name))
         (api-assoc    (%pvec-mk-sym "~A-ASSOC" name))
         
         (empty-vec    (%pvec-mk-sym "%EMPTY-~A" (subseq (string name) 1)))
         (make-filled  (%pvec-mk-sym "%MAKE-FILLED-~A" (subseq (string name) 1)))
         (build-vec    (%pvec-mk-sym "%BUILD-~A-FROM-LIST" (subseq (string name) 1)))
         
         (clone-leaf   (%pvec-mk-sym "~ACLONE-LEAF" conc-name))
         (new-path     (%pvec-mk-sym "~ANEW-PATH" conc-name))
         (push-tail    (%pvec-mk-sym "~APUSH-TAIL" conc-name))
         
         (leaf-type-def (if (eq element-type 't)
                            `(simple-vector ,+branch-factor+)
                            `(simple-array ,element-type (,+branch-factor+))))
         (root-type (if (eq element-type 't)
                        'simple-vector
                        `(simple-array t (*))))
         (tail-type (if (eq element-type 't)
                        'simple-vector
                        `(simple-array ,element-type (*))))
         (make-tail-empty (if (eq element-type 't)
                              `(make-array 0)
                              `(make-array 0 :element-type ',element-type)))
         (make-tail-len (if (eq element-type 't)
                            `(make-array (1+ tail-len))
                            `(make-array (1+ tail-len) :element-type ',element-type)))
         (make-tail-1 (if (eq element-type 't)
                          `(make-array 1)
                          `(make-array 1 :element-type ',element-type)))
         (make-new-tail-len (if (eq element-type 't)
                                `(make-array (length old-tail))
                                `(make-array (length old-tail) :element-type ',element-type))))
    `(progn
       (deftype ,leaf-type () ',leaf-type-def)

       (defstruct (,name (:constructor ,make-name)
                         (:predicate ,pred-name)
                         (:conc-name ,conc-name))
         (count 0 :type fixnum)
         (shift 0 :type fixnum)
         (root #() :type ,root-type)
         (tail ,make-tail-empty :type ,tail-type))

       (defun ,api-count (v) (declare (type ,name v)) (,count-acc v))

       (defun ,api-tail-off (v)
         (declare (type ,name v) (optimize (speed 3) (safety 0)))
         (let ((cnt (,count-acc v)))
           (if (< cnt +branch-factor+) 0 (ash (ash (1- cnt) (- +bit-shift+)) +bit-shift+))))

       (defun ,api-ref (v index &optional not-found)
         (declare (type ,name v)
                  (type fixnum index)
                  (optimize (speed 3) (safety 0)))
         (if (or (< index 0) (>= index (,count-acc v)))
             (values not-found nil)
             (if (>= index (,api-tail-off v))
                 (values (,accessor (,tail-acc v) (logand index +bit-mask+)) t)
                 (let ((node (,root-acc v))
                       (shift (,shift-acc v)))
                   (loop for level-shift from shift downto +bit-shift+ by +bit-shift+
                         do (setf node (svref node (logand (ash index (- level-shift)) +bit-mask+))))
                   (values (,accessor node (logand index +bit-mask+)) t)))))

       (defun ,clone-leaf (leaf)
         (declare (type ,leaf-type leaf) (optimize (speed 3) (safety 0)))
         (copy-seq leaf))

       (defun ,new-path (shift leaf)
         (if (<= shift 0) leaf
             (let ((node (make-array +branch-factor+ :initial-element nil)))
               (setf (svref node 0) (,new-path (- shift +bit-shift+) leaf))
               node)))

       (defun ,push-tail (shift node idx tail-node)
         (let ((new-node (%clone-node node))
               (sub-idx (logand (ash idx (- shift)) +bit-mask+)))
           (if (= shift +bit-shift+)
               (setf (svref new-node sub-idx) tail-node)
               (let ((child (svref node sub-idx)))
                 (if child
                     (setf (svref new-node sub-idx) (,push-tail (- shift +bit-shift+) child idx tail-node))
                     (setf (svref new-node sub-idx) (,new-path (- shift +bit-shift+) tail-node)))))
           new-node))

       (defun ,api-conj (v val)
         (declare (type ,name v) ,@(when (not (eq element-type 't)) `((type ,element-type val))) (optimize (speed 3) (safety 0)))
         (let* ((cnt (,count-acc v))
                (tail (,tail-acc v))
                (tail-len (length tail)))
           (if (< tail-len +branch-factor+)
               (let ((new-tail ,make-tail-len))
                 (replace new-tail tail)
                 (setf (,accessor new-tail tail-len) val)
                 (,make-name :count (1+ cnt) :shift (,shift-acc v) :root (,root-acc v) :tail new-tail))
               (let* ((tail-node tail)
                      (new-tail ,make-tail-1)
                      (root (,root-acc v))
                      (shift (,shift-acc v)))
                 (setf (,accessor new-tail 0) val)
                 (cond
                  ((zerop (length root))
                    (let ((new-root (make-array +branch-factor+)))
                      (setf (svref new-root 0) tail-node)
                      (,make-name :count (1+ cnt) :shift +bit-shift+ :root new-root :tail new-tail)))
                  ((> (ash cnt (- +bit-shift+)) (ash 1 shift))
                    (let ((new-root (make-array +branch-factor+ :initial-element nil)))
                      (setf (svref new-root 0) root)
                      (setf (svref new-root 1) (,new-path shift tail-node))
                      (,make-name :count (1+ cnt) :shift (+ shift +bit-shift+) :root new-root :tail new-tail)))
                  (t (,make-name :count (1+ cnt) :shift shift :root (,push-tail shift root (1- cnt) tail-node) :tail new-tail)))))))

       (defun ,api-assoc (v index new-val)
         (declare (type ,name v) (type fixnum index) ,@(when (not (eq element-type 't)) `((type ,element-type new-val))) (optimize (speed 3) (safety 0)))
         (let ((cnt (,count-acc v)))
           (if (>= index (,api-tail-off v))
               (let* ((old-tail (,tail-acc v))
                      (new-tail ,make-new-tail-len))
                 (replace new-tail old-tail)
                 (setf (,accessor new-tail (logand index +bit-mask+)) new-val)
                 (,make-name :count cnt :shift (,shift-acc v) :root (,root-acc v) :tail new-tail))
               (labels ((update (node level-shift)
                                (if (= level-shift 0)
                                    (let ((new-leaf (,clone-leaf node)))
                                      (setf (,accessor new-leaf (logand index +bit-mask+)) new-val)
                                      new-leaf)
                                    (let ((new-node (%clone-node node))
                                          (child-idx (logand (ash index (- level-shift)) +bit-mask+)))
                                      (setf (svref new-node child-idx)
                                        (update (svref node child-idx)
                                                (- level-shift +bit-shift+)))
                                      new-node))))
                 (,make-name :count cnt :shift (,shift-acc v)
                                :root (update (,root-acc v) (,shift-acc v))
                                :tail (,tail-acc v))))))

       (defparameter ,empty-vec (,make-name))

       (defun ,make-filled (size initial-value)
         (declare (type fixnum size) (optimize (speed 3) (safety 0)))
         (if (<= size 32)
             (let ((tail (make-array size ,@(when (not (eq element-type 't)) `(:element-type ',element-type)) :initial-element initial-value)))
               (,make-name :count size :shift 0 :root #() :tail tail))
             (let* ((tree-count (if (< size 32) 0 (ash (ash (1- size) -5) 5)))
                    (tail-len (- size tree-count))
                    (tail (make-array tail-len ,@(when (not (eq element-type 't)) `(:element-type ',element-type)) :initial-element initial-value))
                    (shared-leaf (make-array 32 ,@(when (not (eq element-type 't)) `(:element-type ',element-type)) :initial-element initial-value))
                    (nodes nil))
               (loop repeat (ash tree-count -5) do (push shared-leaf nodes))
               (let ((shift 0))
                 (loop while (> (length nodes) 1)
                       do (let ((next-level nil) (current nodes))
                            (loop while current
                                  do (let ((internal (make-array 32 :initial-element nil)))
                                       (loop for i from 0 below 32 while current
                                             do (setf (svref internal i) (pop current)))
                                       (push internal next-level)))
                            (setf nodes (nreverse next-level))
                            (incf shift 5)))
                 (,make-name :count size :shift shift :root (car nodes) :tail tail)))))

       (defun ,build-vec (lst)
         (let ((count (length lst)))
           (if (<= count 32)
               (let ((tail (make-array count ,@(when (not (eq element-type 't)) `(:element-type ',element-type)) :initial-element ,fallback-val)))
                 (loop for item in lst for i from 0 do (setf (,accessor tail i) item))
                 (,make-name :count count :shift 0 :root #() :tail tail))
               (let* ((tree-count (if (< count 32) 0 (ash (ash (1- count) -5) 5)))
                      (tail-len (- count tree-count))
                      (tail (make-array tail-len ,@(when (not (eq element-type 't)) `(:element-type ',element-type)) :initial-element ,fallback-val))
                      (nodes nil)
                      (current lst))
                 (loop repeat (ash tree-count -5)
                       do (let ((leaf (make-array 32 ,@(when (not (eq element-type 't)) `(:element-type ',element-type)) :initial-element ,fallback-val)))
                            (loop for i from 0 below 32
                                  do (setf (,accessor leaf i) (car current)
                                           current (cdr current)))
                            (push leaf nodes)))
                 (setf nodes (nreverse nodes))
                 (loop for i from 0 below tail-len
                       do (setf (,accessor tail i) (car current)
                                current (cdr current)))
                 (let ((shift 0))
                   (loop while (> (length nodes) 1)
                         do (let ((next-level nil))
                              (loop for chunk on nodes by (lambda (x) (nthcdr 32 x))
                                    do (let ((internal (make-array 32 :initial-element nil)))
                                         (loop for node in chunk for i from 0 below 32
                                               do (setf (svref internal i) node))
                                         (push internal next-level)))
                              (setf nodes (nreverse next-level))
                              (incf shift 5)))
                   (,make-name :count count :shift shift :root (car nodes) :tail tail))))))))
"""

with open('c:/Users/frank/Projects/FOL/fol/src/collection-primitives.lisp', 'r') as f:
    lines = f.readlines()

new_lines = lines[:36] + [macro_code, '\n(define-pvec-trie %vec-f64 %f64- f64-leaf double-float 0.0d0 aref)\n'] + lines[240:246] + ['(define-pvec-trie %vec-f32 %f32- f32-leaf single-float 0.0f0 aref)\n'] + lines[450:455] + ['(define-pvec-trie %vec-t %t- t-leaf t nil svref)\n'] + lines[659:733] + ['(define-pvec-trie %vec-fix64 %fix64- fix64-leaf fixnum 0 aref)\n'] + lines[938:]

with open('c:/Users/frank/Projects/FOL/fol/src/collection-primitives.lisp', 'w') as f:
    f.writelines(new_lines)

print('Success rewriting lisp file with macro!')
