(require :asdf)
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
        (load quicklisp-init)))
(ql:quickload :fiveam :silent t)
(ql:quickload :named-readtables :silent t)
(ql:quickload :fset :silent t)
(ql:quickload :closer-mop :silent t)
(ql:quickload :trivial-garbage :silent t)
(ql:quickload :bordeaux-threads :silent t)
(ql:quickload :cl-ppcre :silent t)
(ql:quickload :uuid :silent t)
(pushnew (truename "src/") asdf:*central-registry*)
(asdf:load-system "fol-compiler/tests")
;; Run only collections-tests
(fiveam:run! 'fol.compiler.tests::collections-tests)
(sb-ext:exit :code 0)
