(require :asdf)
(let ((ql-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (if (probe-file ql-init)
      (load ql-init)
      (error "QL not found")))
(ql:quickload :fiveam :silent t)
(pushnew (truename "src/") asdf:*central-registry*)
(asdf:load-system :fol-compiler/tests)
(format t "Running persistence tests...~%")
(it.bese.fiveam:run! 'fol.compiler.tests::persistence-tests)
(sb-ext:exit)
