(require :asdf)
(push (truename "src/") asdf:*central-registry*)
(asdf:load-system :fol-compiler)

(in-package :fol.user)
(let ((*readtable* fol.compiler.reader:*fol-readtable*))
  (format t "~%Testing reader with [1 2 3]...~%")
  (let ((v (read-from-string "[1 2 3]")))
    (format t "Read result: ~S~%" v)
    (format t "Type: ~S~%" (type-of v))
    (format t "Class: ~S~%" (class-of v))
    (format t "fol-vector-p: ~S~%" (fol.compiler::fol-vector-p v))
    (format t "Is it a CL vector? ~S~%" (vectorp v))
    (format t "Is it a FOL vector? ~S~%" (typep v 'fol.compiler.collections:<vector>))))
(sb-ext:exit)
