(require 'asdf)
(ql:quickload '("usocket" "bordeaux-threads" "alexandria" "cl-ppcre" "quri" "plump" "trivia" "cl-json" "flexi-streams" "fiveam" "closer-mop" "lparallel" "local-time") :silent t)

(defun get-all-classes ()
  (let ((classes '()))
    (do-all-symbols (sym)
      (when (find-class sym nil)
        (pushnew (find-class sym) classes)))
    classes))

(defun class-slot-counts ()
  (let ((classes (get-all-classes))
        (counts (make-hash-table)))
    (dolist (c classes)
      (when (typep c 'standard-class)
        (unless (sb-mop:class-finalized-p c)
          (ignore-errors (sb-mop:finalize-inheritance c)))
        (when (sb-mop:class-finalized-p c)
          (let ((n (length (sb-mop:class-slots c))))
            (incf (gethash n counts 0))))))
    counts))

(let* ((counts (class-slot-counts))
       (total-classes 0)
       (classes-le-8 0)
       (alist (loop for k being the hash-keys of counts using (hash-value v)
                    collect (cons k v))))
  (setf alist (sort alist #'< :key #'car))
  (dolist (pair alist)
    (let ((n (car pair))
          (c (cdr pair)))
      (incf total-classes c)
      (when (<= n 8)
        (incf classes-le-8 c))
      (format t "~3d slots: ~5d classes~%" n c)))
  (format t "Total classes: ~a~%" total-classes)
  (format t "Classes with <= 8 slots: ~a (~$,%)~%" classes-le-8 (* 100.0 (/ (float classes-le-8) (float total-classes)))))
