(push (truename "src/") asdf:*central-registry*)
(asdf:load-system :fol-compiler)

(defun transpile-file (input-file output-file)
  (with-open-file (in input-file)
    (with-open-file (out output-file :direction :output :if-exists :supersede)
      (format out ";;; Transpiled from ~A by FOL compiler~%~%" (file-namestring input-file))
      (format out ";;; This file was automatically generated. Do not edit directly.~%~%")
      (let ((*readtable* fol.compiler.reader:*fol-readtable*))
        (loop for form = (read in nil :eof)
              until (eq form :eof)
              for result = (fol.compiler:compile-form form)
              do (when (fol.compiler:compilation-result-code result)
                   (let ((code (fol.compiler:compilation-result-code result)))
                     (prin1 code out)
                     (terpri out)
                     (terpri out))))))))

(format t "Transpiling lsim.fol...~%")
(transpile-file "fol-code/lsim.fol" "fol-code/lsim.lisp")
(format t "Transpiling register-8bit.fol...~%")
(transpile-file "fol-code/register-8bit.fol" "fol-code/register-8bit.lisp")
(format t "✓ Done~%")
(sb-ext:quit)
