(push (truename "src/") asdf:*central-registry*)
(asdf:load-system :fol-compiler)

(defun transpile-file (input-file output-file)
  (with-open-file (in input-file)
    (with-open-file (out output-file :direction :output :if-exists :supersede)
      (format out ";;; Transpiled from ~A by FOL compiler~%~%" (file-namestring input-file))
      (format out ";;; This file was automatically generated. Do not edit directly.~%~%")
      (let ((*readtable* fol.compiler.reader:*fol-readtable*)
            (form-count 0)
            (skipped-count 0))
        (loop for form = (read in nil :eof)
              for result = (unless (eq form :eof)
                             (incf form-count)
                             (fol.compiler:compile-form form))
              until (eq form :eof)
              do (if (fol.compiler:compilation-result-code result)
                     (let ((code (fol.compiler:compilation-result-code result)))
                       (prin1 code out)
                       (terpri out)
                       (terpri out))
                     (progn
                       (incf skipped-count)
                       (format t "~%SKIPPED form ~D~%" form-count)
                       (format t "Form name: ~A~%"
                               (if (and (consp form) (symbolp (first form)))
                                   (list (first form) (second form))
                                   "?"))
                       (when (fol.compiler:compilation-result-errors result)
                         (format t "ERROR: ~{~A~%~}~%" (fol.compiler:compilation-result-errors result))))))
        (format t "Total forms: ~D, Skipped: ~D~%" form-count skipped-count)))))

(format t "Transpiling lsim.fol...~%")
(transpile-file "fol-code/lsim.fol" "fol-code/lsim.lisp")
(format t "Transpiling register-8bit.fol...~%")
(transpile-file "fol-code/register-8bit.fol" "fol-code/register-8bit.lisp")
(format t "✓ Done~%")
(sb-ext:quit)
