;;; =============================================================================
;;; Compliance Module - Trade validation in pure Common Lisp with FSet
;;; Equivalent to compliance.fol - demonstrates what FOL provides
;;; =============================================================================

(defpackage :compliance-cl
  (:use :cl)
  (:export #:<trade>
           #:validate-trade
           #:trade-symbol
           #:trade-amount
           #:trade-price
           #:trade-side
           #:make-trade
           #:update-trade))

(in-package :compliance-cl)

;;; ---------------------------------------------------------------------------
;;; 1. Persistent Trade Class using FSet maps
;;;    FOL: (defclass <trade> [<persistent-object>] ...)
;;;    CL: Must manually implement persistence protocol
;;; ---------------------------------------------------------------------------

;; Type marker for dispatch
(defstruct (trade-type (:constructor nil)))

;; A "persistent trade" is an FSet map with a type tag
(defun make-trade (&key symbol amount price side)
  "Create a persistent trade object."
  (fset:map (:type :trade)
            (:symbol symbol)
            (:amount amount)
            (:price price)
            (:side side)))

(defun trade? (obj)
  "Check if OBJ is a trade."
  (and (fset:map? obj)
       (eq (fset:@ obj :type) :trade)))

;; Accessors - must be defined manually for each slot
(defun trade-symbol (trade) (fset:@ trade :symbol))
(defun trade-amount (trade) (fset:@ trade :amount))
(defun trade-price (trade) (fset:@ trade :price))
(defun trade-side (trade) (fset:@ trade :side))

;; Writer functions that return new persistent objects
;; FOL: Automatically generated by defclass
(defun set-trade-symbol (trade value)
  (fset:with trade :symbol value))
(defun set-trade-amount (trade value)
  (fset:with trade :amount value))
(defun set-trade-price (trade value)
  (fset:with trade :price value))
(defun set-trade-side (trade value)
  (fset:with trade :side value))

;;; ---------------------------------------------------------------------------
;;; 2. Business Logic Predicates
;;;    FOL: Uses predicate dispatch with (-> accessor predicate) composition
;;;    CL: Must manually compose accessors and predicates
;;; ---------------------------------------------------------------------------

(defun trade-total-price (trade)
  "Calculate total value of trade."
  (* (trade-price trade) (trade-amount trade)))

(defparameter *restricted-symbols*
  '(AMZN GOOG META MSFT)
  "Symbols that cannot be traded.")

(defun restricted-symbol-p (trade)
  "Check if trade involves a restricted symbol.
   FOL: ([(trade (-> (trade-symbol) (#{AMZN GOOG META MSFT})))] t)"
  (member (trade-symbol trade) *restricted-symbols*))

(defun high-value-p (trade)
  "Check if trade value exceeds $1M.
   FOL: ([(trade (-> (trade-total-price) (> 1000000.00)))] t)"
  (> (trade-total-price trade) 1000000.00))

(defun buy-side-p (trade)
  "Check if trade is a buy order.
   FOL: ([(trade (-> (trade-side) (= :buy)))] t)"
  (eq (trade-side trade) :buy))

(defun penny-stock-p (trade)
  "Check if stock price is below $5.
   FOL: ([(trade (-> (trade-price) (< 5.00)))] t)"
  (< (trade-price trade) 5.00))

(defun penny-stock-buy-p (trade)
  "Check if trade is a penny stock purchase."
  (and (buy-side-p trade) (penny-stock-p trade)))

;;; ---------------------------------------------------------------------------
;;; 3. Validation Function with Manual Predicate Dispatch
;;;    FOL: defgeneric/defmethod with predicate specializers handles ordering
;;;    CL: Must manually order predicates by specificity
;;; ---------------------------------------------------------------------------

(defun validate-trade (trade)
  "Validate a trade according to compliance rules.

   FOL version uses predicate dispatch to automatically order rules:
   (defmethod validate-trade
     ([(trd (restricted-symbol?))] {...})
     ([(trd (high-value?))] {...})
     ([(trd (penny-stock-buy?))] {...})
     ([trd] {...}))

   CL version must manually implement the dispatch cascade."
  (cond
    ;; Rule 1: Block restricted symbols immediately
    ((restricted-symbol-p trade)
     (fset:map (:status :rejected)
               (:reason (format nil "Symbol ~A is on the restricted list"
                                (trade-symbol trade)))))

    ;; Rule 2: Flag high value trades for manual review
    ((high-value-p trade)
     (fset:map (:status :manual-review)
               (:reason "Trade value exceeds $1M limit")))

    ;; Rule 3: Warn on penny stock purchases
    ((penny-stock-buy-p trade)
     (fset:map (:status :warning)
               (:reason "High risk penny stock purchase")
               (:trade trade)))

    ;; Rule 4: Standard approval (Catch-all)
    (t
     (fset:map (:status :approved)
               (:id (gensym "TRD"))))))

;;; ---------------------------------------------------------------------------
;;; 4. Update function for persistent modification
;;;    FOL: Built into the slot protocol
;;;    CL: Must be implemented manually
;;; ---------------------------------------------------------------------------

(defun update-trade (trade &key symbol amount price side)
  "Return a new trade with updated values (persistent update).
   FOL: (assoc trade :price new-price) - built-in"
  (let ((result trade))
    (when symbol (setf result (fset:with result :symbol symbol)))
    (when amount (setf result (fset:with result :amount amount)))
    (when price (setf result (fset:with result :price price)))
    (when side (setf result (fset:with result :side side)))
    result))

;;; =============================================================================
;;; Test Module
;;; =============================================================================

(defpackage :test-compliance-cl
  (:use :cl :compliance-cl))

(in-package :test-compliance-cl)

(defun run-tests ()
  "Run compliance tests."
  ;; Create test trades
  (let ((t1 (make-trade :symbol 'NU :amount 100 :price 18.00 :side :buy))
        (t2 (make-trade :symbol 'GOOG :amount 50 :price 150.00 :side :sell))
        (t3 (make-trade :symbol 'IBM :amount 10000 :price 150.00 :side :buy)))

    (format t "T1: ~A~%" (validate-trade t1))
    ;; => T1: {:status :approved :id TRD123}

    (format t "T2: ~A~%" (validate-trade t2))
    ;; => T2: {:status :rejected :reason "Symbol GOOG is on the restricted list"}

    (format t "T3: ~A~%" (validate-trade t3))))
    ;; => T3: {:status :manual-review :reason "Trade value exceeds $1M limit"}

;; Uncomment to run: (test-compliance-cl::run-tests)
