(require :asdf)
(pushnew #p"c:/Users/frank/Projects/FOL/fol/src/" asdf:*central-registry*)
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (if (probe-file quicklisp-init)
      (load quicklisp-init)
      (format t "Quicklisp not found.~%")))
(asdf:load-system :fol-compiler)
(format t "Ext symbols in FOL.CORE: ~D~%" (let ((count 0)) (do-external-symbols (s :fol.core) (incf count)) count))
(format t "External symbols list starting with A: ~S~%" 
        (let ((syms '())) 
          (do-external-symbols (s :fol.core) 
            (when (char= (char (symbol-name s) 0) #\A)
              (push (symbol-name s) syms)))
          (subseq (sort syms #'string<) 0 (min 5 (length syms)))))
(sb-ext:exit)
