(require :asdf)
(pushnew #p"c:/Users/frank/Projects/FOL/fol/src/" asdf:*central-registry*)
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (if (probe-file quicklisp-init)
      (load quicklisp-init)
      (format t "Quicklisp not found.~%")))
(dolist (dep '(:fset :sycamore :closer-mop :uuid :bordeaux-threads :usocket :cl-ppcre :fiveam))
  (if (find-package :ql)
      (uiop:symbol-call :ql :quickload dep)
      (asdf:load-system dep)))
(asdf:load-system :fol-compiler)
(asdf:load-system :fol-compiler/core)

(defun compile-fol (name)
  (let ((in (format nil "benchmarks/fol-code/~A.fol" name))
        (out (format nil "benchmarks/transpiled-fol-code/~A.lisp" name)))
    (format t "Compiling ~A...~%" name)
    (fol.compiler:compile-file in :output out)))

(dolist (bench '("ast-optimizer-balanced" "compliance" "derived-value-invalidation" "diff" "event-sourcing" "guards" "hierarchical-speculative-execution" "interpreter" "observable"))
  (handler-case (compile-fol bench)
    (error (e) (format t "Error compiling ~A: ~A~%" bench e))))

(sb-ext:exit)
