(require :asdf)
(pushnew #p"c:/Users/frank/Projects/FOL/fol/src/" asdf:*central-registry*)
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (if (probe-file quicklisp-init)
      (load quicklisp-init)
      (format t "Quicklisp not found.~%")))
(dolist (dep '(:fset :sycamore :closer-mop :uuid :bordeaux-threads :usocket :cl-ppcre :fiveam))
  (if (find-package :ql)
      (uiop:symbol-call :ql :quickload dep)
      (asdf:load-system dep)))
(asdf:load-system :fol-compiler)
(format t "Packages found:~%")
(dolist (pkg (list-all-packages))
  (let ((name (package-name pkg)))
    (when (search "FOL" name)
      (format t "  ~A (~D external)~%" name (let ((count 0)) (do-external-symbols (s pkg) (incf count)) count)))))
(finish-output)
(quit)
