(require :asdf)
(pushnew #p"c:/Users/frank/Projects/FOL/fol/src/" asdf:*central-registry*)
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (if (probe-file quicklisp-init)
      (load quicklisp-init)
      (format t "Quicklisp not found.~%")))
(dolist (dep '(:fset :sycamore :closer-mop :uuid :bordeaux-threads :usocket :cl-ppcre :fiveam))
  (if (find-package :ql)
      (uiop:symbol-call :ql :quickload dep)
      (asdf:load-system dep)))
(asdf:load-system :fol-compiler)
(asdf:load-system :fol-compiler/core)
(let ((syms '()))
  (do-external-symbols (s :fol.core)
    (push (symbol-name s) syms))
  (dolist (s (sort syms #'string<))
    (format t "~A~%" s))
  (finish-output))
(quit)
